[general]
title = GoPro Controller

# Camera Type, should be `H3` or `H4`
camera_type = H4

# Take photo by me or not.
take_photo = False

# Delay in minutes
delay = 0

[aws]
bucket = shutter-island
KEY = REDACTED_AWS_ACCESS_KEY_ID
SECRET = REDACTED_AWS_SECRET_ACCESS_KEY

[gopro]
password = REDACTED_GOPRO_PASSWORD
